config/routes.rb
Rails.application.routes.draw do
  resources :users, :pages, :challenges
  root :to => 'users#index'
  post '/logout' => 'sessions#logout'
  post '/login'  => 'sessions#login'

end

app/models/challenge.rb
class Challenge < ActiveRecord::Base
  belongs_to :page
  belongs_to :success_page, class_name: 'Page'
  belongs_to :fail_page, class_name: 'Page'
  has_many   :user_challenges
  has_many   :users, through: :user_challenges

  def fail_next_id
    fail_page_id
  end

  def success_next_id
    success_page_id
  end
end

app/models/page.rb
class Page < ActiveRecord::Base
  has_one  :challenge
  belongs_to :next_page, class_name: 'Page'
  has_many    :prev_pages, class_name: 'Page', foreign_key: 'next_page_id'
  has_many :success_routes, class_name: 'Challenge', foreign_key: 'success_page_id'
  has_many :fail_routes, class_name: 'Challenge', foreign_key: 'fail_page_id'
  has_many :user_pages

  def has_challenge?
    !!challenge
  end

  def next_in_backlog(user)
    sequence = user.read_pages
    i = sequence.index(self)
    sequence[i+1]
  end

  def leads_somewhere?
    has_challenge? || next_page != nil
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :username, :password, presence: true
  validates_uniqueness_of :username, :email
  has_secure_password
  after_create :set_page_one
  has_many :user_challenges
  has_many :challenges, through: :user_challenges
  has_many :user_pages
  has_many :read_pages, through: :user_pages, source: :page

  def authenticate_login(username_email, password)
    if username_email == self.username || username_email == self.email
      authenticate(password)
    else
      false
    end
  end

  def set_page_one
    uid = self.id
    UserPage.create(user_id: uid, page_id: 1)
  end

  def prev_read_page(page)
    i = read_pages.index(page)
    if i>0
      read_pages[i-1]
    else
      read_pages.first
    end
  end

  def farthest_page
    self.read_pages.last
  end

  def return_errors
    if self.errors.messages[:email]
      err = self.errors.messages[:email].first
      return "email error: #{err.capitalize}"
    elsif self.errors.messages[:username]
      err = self.errors.messages[:username].first
      return "username error: #{err.capitalize}"
    elsif self.errors.messages[:password]
      err = self.errors.messages[:password].first
      return "password error: #{err.capitalize}"
    elsif self.errors.messages[:password_confirmation]
      err = self.errors.messages[:password_confirmation].first
      return "password confirmation error: #{err.capitalize}"
    else
      return nil
    end
  end
end

app/models/user_challenge.rb
class UserChallenge < ActiveRecord::Base
  belongs_to :user
  belongs_to :challenge
end

app/models/user_page.rb
class UserPage < ActiveRecord::Base
  validates :page_id, :user_id, presence: true
  belongs_to :user
  belongs_to :page
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
  def current_user
    @current_user || User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController

  def show
    @challenge = Challenge.find(params[:id])
  end

  def update
    @current_user = current_user
    challenge = Challenge.find(params[:id])
    result = UserChallenge.find_or_create_by(user_id: current_user.id, challenge_id: challenge.id, success: params[:success])
    if result.success
      @current_page = challenge.success_page
      UserPage.create(user_id: current_user.id, page_id: @current_page.id)
    else
      @current_page = challenge.fail_page
      UserPage.create(user_id: current_user.id, page_id: @current_page.id)
    end
    redirect_to page_path(@current_page)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def show
    @current_page = Page.find(params[:id])
    @next_page = @current_page.next_page
    @prev_page = current_user.prev_read_page(@current_page)
  end

  def update
    read_page = UserPage.find_or_create_by(user_id: current_user.id, page_id: params[:id])
    redirect_to page_path(read_page.page)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def login
    user = User.all.find do |u|
      u.authenticate_login(params[:username_email], params[:password] )
    end
    if user
      session[:user_id] = user.id
      @current_user = user
      redirect_to user_path(@current_user)
    else
      session[:errors] = "Invalid login credentials"
    end
  end

  def logout
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    if current_user
      redirect_to user_path(current_user)
    else
      render "index"
    end
  end

  def new
    @current_user = User.new
  end

  def create
    @current_user = User.new(user_params)
    if @current_user.save
      session[:user_id] = @current_user.id
      redirect_to user_path(@current_user)
    else
      render :new
    end
  end

  def show
    if current_user
      @current_user = current_user
      @page = @current_user.farthest_page
      redirect_to page_path(@page)
    else
      render "new"
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :username, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProjectRaleighRails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render "shared/navigation" %>
<div class="content">
  <%= yield %>
</div>
</body>
</html>

app/views/pages/_page_back.html.erb
<%= link_to page_path(@prev_page) do  %>
  <div class="prev-flip">Replace with shape</div>
<% end %>

app/views/pages/_page_next.html.erb
<% if @current_page.has_challenge?  %>
  <%= link_to challenge_path(@current_page.challenge) do  %>
    <div class="next-flip">Replace with next shape</div>
  <% end %>
<% else %>
  <%= link_to page_path(@next_page), method: :patch do  %>
    <div class="next-flip">Replace with next shape</div>
  <% end %>
<% end %>

app/views/pages/show.html.erb
<table class="page-table">
  <tr>
    <td> <%= render "page_back" %> </td>
    <td class="open-page">
      <p><%= @current_page.body %> </p>
      <p><%= @current_page.id.to_s + "....just for testing "%></p>
    </td>
    <td> <%= render "page_next" %> </td>
  </tr>

</table>

app/views/shared/_navigation.html.erb
<nav>
  <% if current_user %>
    <%= button_to "Logout", "/logout" %>
  <% end %>
</nav>

app/views/users/index.html.erb
<h1>Log In</h1>
<p class="error">
  <%= session[:errors] if session[:errors] %>
</p>
<%= form_tag "/login" do %>
  <%= label_tag "email or username" %>
  <%= text_field_tag :username_email %>
  <%= label_tag :password %>
  <%= password_field_tag :password %>
  <%= submit_tag %>
<% end %>

<br>

<%= render template: "users/new" %>

app/views/users/new.html.erb
<h3 class="error-heading">
  <% if current_user %>
  <%= @current_user.errors.messages if @current_user.errors.messages.any? %>
  <% end %>
</h3>

<h1>Sign your copy of the book</h1>
<ul>
<%= form_for(:user) do |f| %>
  <li>
    <%= f.label :username  %>
    <%= f.text_field :username %>
  </li>
  <li>
    <%= f.label :email %>
    <%= f.email_field :email %>
  </li>
  <li>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </li>
  <li>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </li>
  <li> <%= f.submit %> </li>
<% end %>
</ul>